let level1;

function initLevel() {
  level1 = new Level(
    [
      new Chicken(800),
      new ChickenSmall(1000),
      new Chicken(1200),
      new ChickenSmall(1400),
      new Chicken(1600),
      new ChickenSmall(1800),
      new Chicken(2000),
      new ChickenSmall(2200),
      new Chicken(2400),
      new ChickenSmall(2600),
      new Chicken(2800),
      new ChickenSmall(3000),
      new Chicken(3200),
      new ChickenSmall(3400),
      new Chicken(3600),
      new ChickenSmall(3800),
      new Chicken(4000),
      new ChickenSmall(4200),
      new Chicken(4400),
      new ChickenSmall(4600),
      new Endboss(),
    ],
    [
      new Cloud(),
      new Cloud(),
      new Cloud(),
      new Cloud(),
      new Cloud(),
      new Cloud(),
      new Cloud(),
      new Cloud(),
    ],
    [
      new BackgroundObject('img/5_background/layers/air.png', -719),
      new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
      new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
      new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
      new BackgroundObject('img/5_background/layers/air.png', 0),
      new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
      new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
      new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
      new BackgroundObject('img/5_background/layers/air.png', 719),
      new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
      new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
      new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
      new BackgroundObject(
        'img/5_background/layers/3_third_layer/1.png',
        719 * 2,
      ),
      new BackgroundObject(
        'img/5_background/layers/2_second_layer/1.png',
        719 * 2,
      ),
      new BackgroundObject(
        'img/5_background/layers/1_first_layer/1.png',
        719 * 2,
      ),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
      new BackgroundObject(
        'img/5_background/layers/3_third_layer/2.png',
        719 * 3,
      ),
      new BackgroundObject(
        'img/5_background/layers/2_second_layer/2.png',
        719 * 3,
      ),
      new BackgroundObject(
        'img/5_background/layers/1_first_layer/2.png',
        719 * 3,
      ),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 4),
      new BackgroundObject(
        'img/5_background/layers/3_third_layer/1.png',
        719 * 4,
      ),
      new BackgroundObject(
        'img/5_background/layers/2_second_layer/1.png',
        719 * 4,
      ),
      new BackgroundObject(
        'img/5_background/layers/1_first_layer/1.png',
        719 * 4,
      ),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 5),
      new BackgroundObject(
        'img/5_background/layers/3_third_layer/2.png',
        719 * 5,
      ),
      new BackgroundObject(
        'img/5_background/layers/2_second_layer/2.png',
        719 * 5,
      ),
      new BackgroundObject(
        'img/5_background/layers/1_first_layer/2.png',
        719 * 5,
      ),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 6),
      new BackgroundObject(
        'img/5_background/layers/3_third_layer/1.png',
        719 * 6,
      ),
      new BackgroundObject(
        'img/5_background/layers/2_second_layer/1.png',
        719 * 6,
      ),
      new BackgroundObject(
        'img/5_background/layers/1_first_layer/1.png',
        719 * 6,
      ),
      new BackgroundObject('img/5_background/layers/air.png', 719 * 7),
      new BackgroundObject(
        'img/5_background/layers/3_third_layer/2.png',
        719 * 7,
      ),
      new BackgroundObject(
        'img/5_background/layers/2_second_layer/2.png',
        719 * 7,
      ),
      new BackgroundObject(
        'img/5_background/layers/1_first_layer/2.png',
        719 * 7,
      ),
    ],
    [
      new Coin(600),
      new Coin(1400),
      new Coin(2200),
      new Coin(3000),
      new Coin(3800),
    ],
    [
      new Bottle(400),
      new Bottle(650),
      new Bottle(900),
      new Bottle(1150),
      new Bottle(1400),
      new Bottle(1650),
      new Bottle(1900),
      new Bottle(2150),
      new Bottle(2400),
      new Bottle(2650),
      new Bottle(2900),
      new Bottle(3150),
      new Bottle(3400),
      new Bottle(3650),
      new Bottle(3900),
      new Bottle(4150),
    ],
  );
}
