const level1 = new Level(
  [
    new Chicken(500),
    new ChickenSmall(700),
    new Chicken(900),
    new ChickenSmall(1100),
    new Chicken(1300),
    new ChickenSmall(1500),
    new Chicken(1700),
    new ChickenSmall(1850),
    new Chicken(2000),
    new ChickenSmall(2150),
    new Endboss(),
  ],
  [new Cloud(), new Cloud(), new Cloud(), new Cloud(), new Cloud()],
  [
    new BackgroundObject('img/5_background/layers/air.png', -719),
    new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
    new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
    new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
    new BackgroundObject('img/5_background/layers/air.png', 0),
    new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
    new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
    new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
    new BackgroundObject('img/5_background/layers/air.png', 719),
    new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
    new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
    new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
    new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
    new BackgroundObject(
      'img/5_background/layers/3_third_layer/1.png',
      719 * 2,
    ),
    new BackgroundObject(
      'img/5_background/layers/2_second_layer/1.png',
      719 * 2,
    ),
    new BackgroundObject(
      'img/5_background/layers/1_first_layer/1.png',
      719 * 2,
    ),
    new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
    new BackgroundObject(
      'img/5_background/layers/3_third_layer/2.png',
      719 * 3,
    ),
    new BackgroundObject(
      'img/5_background/layers/2_second_layer/2.png',
      719 * 3,
    ),
    new BackgroundObject(
      'img/5_background/layers/1_first_layer/2.png',
      719 * 3,
    ),
  ],
  [new Coin(), new Coin(), new Coin(), new Coin(), new Coin()],
  [
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
  ],
);
