const level1 = new Level(
  [
    new Chicken(500),
    new ChickenSmall(700),
    new Chicken(900),
    new ChickenSmall(1100),
    new Chicken(1300),
    new ChickenSmall(1500),
    new Chicken(1700),
    new ChickenSmall(1900),
    new Chicken(2100),
    new ChickenSmall(2300),
    new Chicken(2500),
    new ChickenSmall(2700),
    new Chicken(2900),
    new ChickenSmall(3100),
    new Chicken(3300),
    new ChickenSmall(3500),
    new Chicken(3700),
    new ChickenSmall(3900),
    new Chicken(4100),
    new ChickenSmall(4300),
    new Endboss(),
  ],
  [
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
  ],
  [
    new BackgroundObject('img/5_background/layers/air.png', -719),
    new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
    new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
    new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
    new BackgroundObject('img/5_background/layers/air.png', 0),
    new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
    new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
    new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
    new BackgroundObject('img/5_background/layers/air.png', 719),
    new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
    new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
    new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
    new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
    new BackgroundObject(
      'img/5_background/layers/3_third_layer/1.png',
      719 * 2,
    ),
    new BackgroundObject(
      'img/5_background/layers/2_second_layer/1.png',
      719 * 2,
    ),
    new BackgroundObject(
      'img/5_background/layers/1_first_layer/1.png',
      719 * 2,
    ),
    new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
    new BackgroundObject(
      'img/5_background/layers/3_third_layer/2.png',
      719 * 3,
    ),
    new BackgroundObject(
      'img/5_background/layers/2_second_layer/2.png',
      719 * 3,
    ),
    new BackgroundObject(
      'img/5_background/layers/1_first_layer/2.png',
      719 * 3,
    ),
    new BackgroundObject('img/5_background/layers/air.png', 719 * 4),
    new BackgroundObject(
      'img/5_background/layers/3_third_layer/1.png',
      719 * 4,
    ),
    new BackgroundObject(
      'img/5_background/layers/2_second_layer/1.png',
      719 * 4,
    ),
    new BackgroundObject(
      'img/5_background/layers/1_first_layer/1.png',
      719 * 4,
    ),
    new BackgroundObject('img/5_background/layers/air.png', 719 * 5),
    new BackgroundObject(
      'img/5_background/layers/3_third_layer/2.png',
      719 * 5,
    ),
    new BackgroundObject(
      'img/5_background/layers/2_second_layer/2.png',
      719 * 5,
    ),
    new BackgroundObject(
      'img/5_background/layers/1_first_layer/2.png',
      719 * 5,
    ),
    new BackgroundObject('img/5_background/layers/air.png', 719 * 6),
    new BackgroundObject(
      'img/5_background/layers/3_third_layer/1.png',
      719 * 6,
    ),
    new BackgroundObject(
      'img/5_background/layers/2_second_layer/1.png',
      719 * 6,
    ),
    new BackgroundObject(
      'img/5_background/layers/1_first_layer/1.png',
      719 * 6,
    ),
    new BackgroundObject('img/5_background/layers/air.png', 719 * 7),
    new BackgroundObject(
      'img/5_background/layers/3_third_layer/2.png',
      719 * 7,
    ),
    new BackgroundObject(
      'img/5_background/layers/2_second_layer/2.png',
      719 * 7,
    ),
    new BackgroundObject(
      'img/5_background/layers/1_first_layer/2.png',
      719 * 7,
    ),
  ],
  [new Coin(600), new Coin(1400), new Coin(2200), new Coin(3000), new Coin(3800)],
  [
    new Bottle(400),
    new Bottle(650),
    new Bottle(900),
    new Bottle(1150),
    new Bottle(1400),
    new Bottle(1650),
    new Bottle(1900),
    new Bottle(2150),
    new Bottle(2400),
    new Bottle(2650),
    new Bottle(2900),
    new Bottle(3150),
    new Bottle(3400),
    new Bottle(3650),
    new Bottle(3900),
    new Bottle(4150),
  ],
);
